import type { ListingData, FeedData } from '@/types'

const IMGS = [
  'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
  'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
  'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
  'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
  'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80',
  'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&q=80',
  'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
  'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80',
  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
]

export const MOCK_LISTINGS: ListingData[] = [
  {
    id: 1,
    userId: 'u1',
    title: 'Офіс з видом на море, Приморський',
    type: 'Офіс',
    price: 28000,
    area: 145,
    floor: 5,
    totalFloors: 9,
    district: 'Приморський',
    address: 'вул. Дерибасівська, 18, Одеса',
    city: 'Одеса',
    condition: 'Євроремонт',
    parking: true,
    separateEntrance: true,
    description: 'Представницький офіс у серці Одеси. Відкрите планування, великі вікна з видом на море та Приморський бульвар. Ідеально для IT-компаній та консалтингових фірм.',
    images: [IMGS[0], IMGS[8]],
    features: ['Паркінг', 'Окремий вхід', 'Ліфт', 'Кондиціонер', 'Охорона'],
    isActive: true,
    views: 312,
    likes: 24,
    score: 980,
    isPromoted: true,
    isFeatured: true,
    promotedUntil: null,
    createdAt: new Date(Date.now() - 5 * 24 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
    ownerName: 'Арсен Мерідіан',
    ownerPhone: '+380671234567',
  },
  {
    id: 2,
    userId: 'u2',
    title: 'Торгова площа в ТРЦ "Європа"',
    type: 'Рітейл',
    price: 24000,
    area: 82,
    floor: 2,
    totalFloors: 3,
    district: 'Київський',
    address: 'просп. Академіка Глушка, 11, Одеса',
    city: 'Одеса',
    condition: 'Shell & Core',
    parking: true,
    separateEntrance: false,
    description: 'Торгова площа у прохідному торговому центрі на Таїрова. Висока прохідність, зручне розташування поруч зупинок транспорту.',
    images: [IMGS[1]],
    features: ['Великий трафік', 'Паркінг', 'Вантажний ліфт', 'Відеоспостереження'],
    isActive: true,
    views: 456,
    likes: 18,
    score: 890,
    isPromoted: false,
    isNew: false,
    promotedUntil: null,
    createdAt: new Date(Date.now() - 3 * 24 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
    ownerName: 'Марина Ковальчук',
    ownerPhone: '+380672345678',
  },
  {
    id: 3,
    userId: 'u3',
    title: 'Склад з пандусом, Пересипь',
    type: 'Склад',
    price: 15000,
    area: 380,
    floor: 1,
    totalFloors: 1,
    district: 'Суворовський',
    address: 'вул. Хімічна, 7, Одеса',
    city: 'Одеса',
    condition: 'Задовільний',
    parking: true,
    separateEntrance: true,
    description: 'Просторий склад з виїздом на обʼїзну дорогу. Пандус для вантажних автомобілів, охорона 24/7. Зручна логістика — поруч Одеський порт.',
    images: [IMGS[2]],
    features: ['Пандус', 'Ворота 4.5м', 'Охорона 24/7', 'Вага', '3-фазна електрика'],
    isActive: true,
    views: 89,
    likes: 5,
    score: 450,
    isPromoted: false,
    isNew: true,
    promotedUntil: null,
    createdAt: new Date(Date.now() - 1 * 24 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
    ownerName: 'Сергій Лисенко',
    ownerPhone: '+380673456789',
  },
  {
    id: 4,
    userId: 'u2',
    title: 'Приміщення під кафе на Аркадії',
    type: 'Кафе/Ресторан',
    price: 20000,
    area: 105,
    floor: 1,
    totalFloors: 4,
    district: 'Приморський',
    address: 'вул. Генуезька, 24, Одеса',
    city: 'Одеса',
    condition: 'Євроремонт',
    parking: false,
    separateEntrance: true,
    description: 'Готове приміщення під ресторан або кафе біля пляжу Аркадія. Витяжка, вентиляція встановлені. Є літня тераса з видом на море.',
    images: [IMGS[3]],
    features: ['Витяжка', 'Тераса', 'Окремий вхід', 'Перша лінія', 'Вентиляція'],
    isActive: true,
    views: 234,
    likes: 21,
    score: 870,
    isPromoted: false,
    isNew: true,
    isFeatured: false,
    promotedUntil: null,
    createdAt: new Date(Date.now() - 2 * 24 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
    ownerName: 'Марина Ковальчук',
    ownerPhone: '+380672345678',
  },
  {
    id: 5,
    userId: 'u4',
    title: 'Салон краси / студія на Фонтані',
    type: 'Салон',
    price: 12000,
    area: 60,
    floor: 1,
    totalFloors: 5,
    district: 'Приморський',
    address: 'вул. Фонтанська дорога, 51, Одеса',
    city: 'Одеса',
    condition: 'Євроремонт',
    parking: false,
    separateEntrance: true,
    description: 'Затишне приміщення для салону краси або студії у жвавому районі Великого Фонтану. Сантехніка підведена, є зона ресепшн.',
    images: [IMGS[4], IMGS[9]],
    features: ['Сантехніка', 'Ресепшн', 'Окремий вхід', 'Кондиціонер'],
    isActive: true,
    views: 145,
    likes: 12,
    score: 620,
    isPromoted: false,
    isNew: true,
    promotedUntil: null,
    createdAt: new Date(Date.now() - 4 * 24 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
    ownerName: 'Наталія Бондар',
    ownerPhone: '+380674567890',
  },
  {
    id: 6,
    userId: 'u1',
    title: 'Шоурум / лофт на Молдаванці',
    type: 'Шоурум',
    price: 16500,
    area: 90,
    floor: 2,
    totalFloors: 4,
    district: 'Приморський',
    address: 'вул. Мала Арнаутська, 46, Одеса',
    city: 'Одеса',
    condition: 'Євроремонт',
    parking: true,
    separateEntrance: false,
    description: 'Стильний лофт-простір в історичному центрі Одеси. Високі стелі, великі вітрини. Підходить для шоуруму, дизайн-студії, фотостудії.',
    images: [IMGS[5]],
    features: ['Лофт-стиль', 'Вітрини', 'Паркінг', 'Переговорні кімнати'],
    isActive: true,
    views: 178,
    likes: 19,
    score: 750,
    isPromoted: false,
    isFeatured: true,
    promotedUntil: null,
    createdAt: new Date(Date.now() - 6 * 24 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
    ownerName: 'Арсен Мерідіан',
    ownerPhone: '+380671234567',
  },
  {
    id: 7,
    userId: 'u5',
    title: 'Co-working на Французькому бульварі',
    type: 'Гнучкий простір',
    price: 8500,
    area: 40,
    floor: 3,
    totalFloors: 7,
    district: 'Приморський',
    address: 'Французький бульвар, 22, Одеса',
    city: 'Одеса',
    condition: 'Євроремонт',
    parking: false,
    separateEntrance: false,
    description: 'Готовий гнучкий простір з меблями, інтернетом та всією інфраструктурою. Від 1 місяця. Ідеально для стартапів та фрілансерів.',
    images: [IMGS[6]],
    features: ['Меблі включено', 'Інтернет 1Gbps', 'Переговорна', 'Кава/чай', 'Від 1 міс'],
    isActive: true,
    views: 67,
    likes: 8,
    score: 340,
    isPromoted: false,
    isNew: true,
    promotedUntil: null,
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
    ownerName: 'Катерина Сайко',
    ownerPhone: '+380675678901',
  },
  {
    id: 8,
    userId: 'u3',
    title: 'Офіс в БЦ "Мерідіан"',
    type: 'Офіс',
    price: 38000,
    area: 200,
    floor: 8,
    totalFloors: 16,
    district: 'Київський',
    address: 'просп. Небесної Сотні, 5, Одеса',
    city: 'Одеса',
    condition: 'Євроремонт',
    parking: true,
    separateEntrance: false,
    description: 'Престижний офіс класу А у сучасному бізнес-центрі. Панорамний вид на місто, повна інфраструктура. Ідеально для великих компаній.',
    images: [IMGS[7], IMGS[0]],
    features: ['Клас А', 'Панорама', 'Підземний паркінг', 'Ресепшн', 'Security'],
    isActive: true,
    views: 389,
    likes: 35,
    score: 1100,
    isPromoted: true,
    isFeatured: true,
    promotedUntil: null,
    createdAt: new Date(Date.now() - 7 * 24 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
    ownerName: 'Сергій Лисенко',
    ownerPhone: '+380673456789',
  },
]

export function getMockFeed(): FeedData {
  return {
    populyarni: [...MOCK_LISTINGS].sort((a, b) => b.views - a.views).slice(0, 5),
    novi: MOCK_LISTINGS.filter(l => l.isNew).slice(0, 6),
    rekomendovani: MOCK_LISTINGS.filter(l => l.isFeatured || l.isPromoted).slice(0, 8),
  }
}
